-- Generated by Oracle SQL Developer Data Modeler 3.1.4.710
--   at:        2013-12-14 21:10:05 CET
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



CREATE TABLE STAR_Datum 
    ( 
     id NUMBER (10)  NOT NULL , 
     mesiac NUMBER (10) , 
     den NUMBER (10) , 
     rok NUMBER (10) 
    ) 
;


CREATE INDEX STAR_Datum__IDXv1 ON STAR_Datum 
    ( 
     den ASC 
    ) 
;
CREATE INDEX STAR_Datum__IDXv2 ON STAR_Datum 
    ( 
     mesiac ASC 
    ) 
;
CREATE INDEX STAR_Datum__IDXv3 ON STAR_Datum 
    ( 
     rok ASC 
    ) 
;
CREATE INDEX STAR_Datum__IDXv4 ON STAR_Datum 
    ( 
     id ASC 
    ) 
;

ALTER TABLE STAR_Datum 
    ADD CONSTRAINT STAR_Time_PK PRIMARY KEY ( id ) ;



CREATE TABLE STAR_Events 
    ( 
     id NUMBER (10)  NOT NULL , 
     creator VARCHAR2 (256) , 
     description NCLOB , 
     datum_id NUMBER (10)  NOT NULL , 
     povod_id NUMBER (10)  NOT NULL , 
     repository_id NUMBER (10)  NOT NULL 
    ) 
;


CREATE INDEX STAR_Events__IDXv1 ON STAR_Events 
    ( 
     id ASC 
    ) 
;

ALTER TABLE STAR_Events 
    ADD CONSTRAINT STAR_Events_PK PRIMARY KEY ( id ) ;



CREATE TABLE STAR_Issue 
    ( 
     id NUMBER (10)  NOT NULL , 
     title VARCHAR2 (256) , 
     body NCLOB , 
     datum_id NUMBER (10)  NOT NULL , 
     povod_id NUMBER (10)  NOT NULL , 
     repository_id NUMBER (10)  NOT NULL , 
     jazyk_id NUMBER (10) 
    ) 
;


CREATE INDEX STAR_Issue__IDXv1 ON STAR_Issue 
    ( 
     id ASC 
    ) 
;

ALTER TABLE STAR_Issue 
    ADD CONSTRAINT STAR_Issue_PK PRIMARY KEY ( id ) ;



CREATE TABLE STAR_Jazyk 
    ( 
     id NUMBER (10)  NOT NULL , 
     meno VARCHAR2 (256) 
    ) 
;


CREATE UNIQUE INDEX STAR_Jazyk__IDXv1 ON STAR_Jazyk 
    ( 
     meno ASC 
    ) 
;
CREATE INDEX STAR_Jazyk__IDXv2 ON STAR_Jazyk 
    ( 
     id ASC 
    ) 
;

ALTER TABLE STAR_Jazyk 
    ADD CONSTRAINT STAR_Jazyk_PK PRIMARY KEY ( id ) ;



CREATE TABLE STAR_Pocet_Issue 
    ( 
     id NUMBER (10)  NOT NULL , 
     num_issues NUMBER (10) , 
     time_id NUMBER (10)  NOT NULL , 
     repository_id NUMBER (10)  NOT NULL , 
     povod_id NUMBER (10)  NOT NULL 
    ) 
;


CREATE INDEX STAR_Pocet_Issue__IDXv1 ON STAR_Pocet_Issue 
    ( 
     id ASC 
    ) 
;

ALTER TABLE STAR_Pocet_Issue 
    ADD CONSTRAINT STAR_Pocet_Issue_PK PRIMARY KEY ( id ) ;



CREATE TABLE STAR_Pocet_clenov_timu 
    ( 
     id NUMBER (10)  NOT NULL , 
     num_users_in_team NUMBER (10)  NOT NULL , 
     povod_id NUMBER (10)  NOT NULL , 
     team_id NUMBER (10)  NOT NULL 
    ) 
;


CREATE INDEX STAR_Pocet_clenov_timu__IDXv1 ON STAR_Pocet_clenov_timu 
    ( 
     id ASC 
    ) 
;

ALTER TABLE STAR_Pocet_clenov_timu 
    ADD CONSTRAINT STAR_Num_User_team_PK PRIMARY KEY ( id ) ;



CREATE TABLE STAR_Pocet_issue_za_mesiac 
    ( 
     id NUMBER (10)  NOT NULL , 
     pocet_issue NUMBER (10) , 
     povod_id NUMBER (10)  NOT NULL , 
     mesiace_roky_id NUMBER (10)  NOT NULL , 
     minimum_v_mesiaci NUMBER (10) , 
     maximum_v_mesiaci NUMBER (10) 
    ) 
;


CREATE INDEX STAR_Pocet_issuemesiac__IDXv1 ON STAR_Pocet_issue_za_mesiac 
    ( 
     id ASC 
    ) 
;

ALTER TABLE STAR_Pocet_issue_za_mesiac 
    ADD CONSTRAINT STAR_Pocet_issue_za_mesiac_PK PRIMARY KEY ( id ) ;



CREATE TABLE STAR_Pocet_issue_za_rok 
    ( 
     id NUMBER (10)  NOT NULL , 
     pocet_issue NUMBER (10) , 
     povod_id NUMBER (10)  NOT NULL , 
     rok_id NUMBER (10)  NOT NULL , 
     minimum_v_roku NUMBER (10) , 
     maximum_v_roku NUMBER (10) 
    ) 
;


CREATE INDEX STAR_Pocet_issue_za_rok__IDXv1 ON STAR_Pocet_issue_za_rok 
    ( 
     id ASC 
    ) 
;

ALTER TABLE STAR_Pocet_issue_za_rok 
    ADD CONSTRAINT STAR_Pocet_issue_za_rok_PK PRIMARY KEY ( id ) ;



CREATE TABLE STAR_Pocet_pouzivatelov 
    ( 
     id NUMBER (10)  NOT NULL , 
     pocet_pouzivatelov NUMBER (10) , 
     povod_id NUMBER (10)  NOT NULL 
    ) 
;


CREATE INDEX STAR_Pocet_pouzivatelov__IDXv1 ON STAR_Pocet_pouzivatelov 
    ( 
     id ASC 
    ) 
;

ALTER TABLE STAR_Pocet_pouzivatelov 
    ADD CONSTRAINT STAR_Pocet_usr_PK PRIMARY KEY ( id ) ;



CREATE TABLE STAR_Pouzivatelia 
    ( 
     id NUMBER (10)  NOT NULL , 
     meno VARCHAR2 (256) , 
     avatar VARCHAR2 (512) , 
     url VARCHAR2 (512) , 
     povod_id NUMBER (10)  NOT NULL 
    ) 
;


CREATE INDEX STAR_Pouzivatelia__IDXv1 ON STAR_Pouzivatelia 
    ( 
     id ASC 
    ) 
;

ALTER TABLE STAR_Pouzivatelia 
    ADD CONSTRAINT STAR_POUZIVATELIA_PK PRIMARY KEY ( id ) ;



CREATE TABLE STAR_Povod 
    ( 
     id NUMBER (10)  NOT NULL , 
     name VARCHAR2 (256) 
    ) 
;


CREATE INDEX STAR_Povod__IDXv1 ON STAR_Povod 
    ( 
     id ASC 
    ) 
;

ALTER TABLE STAR_Povod 
    ADD CONSTRAINT STAR_Povod_PK PRIMARY KEY ( id ) ;



CREATE TABLE STAR_Repository 
    ( 
     id NUMBER (10)  NOT NULL , 
     name VARCHAR2 (256) , 
     owner VARCHAR2 (256) 
    ) 
;


CREATE INDEX STAR_Repository__IDXv1 ON STAR_Repository 
    ( 
     name ASC 
    ) 
;
CREATE INDEX STAR_Repository__IDXv2 ON STAR_Repository 
    ( 
     id ASC 
    ) 
;

ALTER TABLE STAR_Repository 
    ADD CONSTRAINT STAR_Repository_PK PRIMARY KEY ( id ) ;



CREATE TABLE STAR_Tim 
    ( 
     id NUMBER (10)  NOT NULL , 
     name VARCHAR2 (256) 
    ) 
;


CREATE INDEX STAR_Tim__IDXv1 ON STAR_Tim 
    ( 
     id ASC 
    ) 
;

ALTER TABLE STAR_Tim 
    ADD CONSTRAINT STAR_Team_PK PRIMARY KEY ( id ) ;



CREATE TABLE STAR_mesiace_roky 
    ( 
     id NUMBER (10)  NOT NULL , 
     rok NUMBER (10) , 
     mesiac NUMBER (10) 
    ) 
;


CREATE INDEX STAR_mesiace_roky__IDXv1 ON STAR_mesiace_roky 
    ( 
     id ASC 
    ) 
;

ALTER TABLE STAR_mesiace_roky 
    ADD CONSTRAINT STAR_mesiace_roky_PK PRIMARY KEY ( id ) ;



CREATE TABLE STAR_roky 
    ( 
     id NUMBER (10)  NOT NULL , 
     rok NUMBER (10) 
    ) 
;


CREATE INDEX STAR_roky__IDXv1 ON STAR_roky 
    ( 
     id ASC 
    ) 
;

ALTER TABLE STAR_roky 
    ADD CONSTRAINT STAR_roky_PK PRIMARY KEY ( id ) ;




ALTER TABLE STAR_Events 
    ADD CONSTRAINT STAR_EVENTS_Povod_FK FOREIGN KEY 
    ( 
     povod_id
    ) 
    REFERENCES STAR_Povod 
    ( 
     id
    ) 
;


ALTER TABLE STAR_Events 
    ADD CONSTRAINT STAR_EVENTS_Repository_FK FOREIGN KEY 
    ( 
     repository_id
    ) 
    REFERENCES STAR_Repository 
    ( 
     id
    ) 
;


ALTER TABLE STAR_Events 
    ADD CONSTRAINT STAR_Events_STAR_Datum_FK FOREIGN KEY 
    ( 
     datum_id
    ) 
    REFERENCES STAR_Datum 
    ( 
     id
    ) 
;


ALTER TABLE STAR_Issue 
    ADD CONSTRAINT STAR_ISSUEDatum_FK FOREIGN KEY 
    ( 
     datum_id
    ) 
    REFERENCES STAR_Datum 
    ( 
     id
    ) 
;


ALTER TABLE STAR_Issue 
    ADD CONSTRAINT STAR_ISSUEJazyk_FK FOREIGN KEY 
    ( 
     jazyk_id
    ) 
    REFERENCES STAR_Jazyk 
    ( 
     id
    ) 
;


ALTER TABLE STAR_Issue 
    ADD CONSTRAINT STAR_ISSUEPovod_FK FOREIGN KEY 
    ( 
     povod_id
    ) 
    REFERENCES STAR_Povod 
    ( 
     id
    ) 
;


ALTER TABLE STAR_Issue 
    ADD CONSTRAINT STAR_ISSUERepository_FK FOREIGN KEY 
    ( 
     repository_id
    ) 
    REFERENCES STAR_Repository 
    ( 
     id
    ) 
;


ALTER TABLE STAR_Pocet_clenov_timu 
    ADD CONSTRAINT STAR_PCLTIMUPovod_FK FOREIGN KEY 
    ( 
     povod_id
    ) 
    REFERENCES STAR_Povod 
    ( 
     id
    ) 
;


ALTER TABLE STAR_Pocet_clenov_timu 
    ADD CONSTRAINT STAR_PCLTIMUTeam_FK FOREIGN KEY 
    ( 
     team_id
    ) 
    REFERENCES STAR_Tim 
    ( 
     id
    ) 
;


ALTER TABLE STAR_Pocet_issue_za_mesiac 
    ADD CONSTRAINT STAR_PISSMESPovod_FK FOREIGN KEY 
    ( 
     povod_id
    ) 
    REFERENCES STAR_Povod 
    ( 
     id
    ) 
;


ALTER TABLE STAR_Pocet_issue_za_mesiac 
    ADD CONSTRAINT STAR_PISSMESmesiace_roky_FK FOREIGN KEY 
    ( 
     mesiace_roky_id
    ) 
    REFERENCES STAR_mesiace_roky 
    ( 
     id
    ) 
;


ALTER TABLE STAR_Pocet_issue_za_rok 
    ADD CONSTRAINT STAR_PISSROKPovod_FK FOREIGN KEY 
    ( 
     povod_id
    ) 
    REFERENCES STAR_Povod 
    ( 
     id
    ) 
;


ALTER TABLE STAR_Pocet_issue_za_rok 
    ADD CONSTRAINT STAR_PISSROKroky_FK FOREIGN KEY 
    ( 
     rok_id
    ) 
    REFERENCES STAR_roky 
    ( 
     id
    ) 
;


ALTER TABLE STAR_Pocet_Issue 
    ADD CONSTRAINT STAR_PISSUEPovod_FK FOREIGN KEY 
    ( 
     povod_id
    ) 
    REFERENCES STAR_Povod 
    ( 
     id
    ) 
;


ALTER TABLE STAR_Pocet_Issue 
    ADD CONSTRAINT STAR_PISSUERepository_FK FOREIGN KEY 
    ( 
     repository_id
    ) 
    REFERENCES STAR_Repository 
    ( 
     id
    ) 
;


ALTER TABLE STAR_Pocet_Issue 
    ADD CONSTRAINT STAR_PISSUETime_FK FOREIGN KEY 
    ( 
     time_id
    ) 
    REFERENCES STAR_Datum 
    ( 
     id
    ) 
;


ALTER TABLE STAR_Pouzivatelia 
    ADD CONSTRAINT STAR_POUZIVATELIAPovod_FK FOREIGN KEY 
    ( 
     povod_id
    ) 
    REFERENCES STAR_Povod 
    ( 
     id
    ) 
;


ALTER TABLE STAR_Pocet_pouzivatelov 
    ADD CONSTRAINT STAR_PPOUZIVATELOVPovod_FK FOREIGN KEY 
    ( 
     povod_id
    ) 
    REFERENCES STAR_Povod 
    ( 
     id
    ) 
;

CREATE SEQUENCE STAR_Datum_id_SEQ 
    NOCACHE 
    ORDER ;

CREATE OR REPLACE TRIGGER STAR_Datum_id_TRG 
BEFORE INSERT ON STAR_Datum 
FOR EACH ROW 
WHEN (NEW.id IS NULL) 
BEGIN 
    SELECT STAR_Datum_id_SEQ.NEXTVAL INTO :NEW.id FROM DUAL; 
END;
/

CREATE SEQUENCE STAR_Events_id_SEQ 
    NOCACHE 
    ORDER ;

CREATE OR REPLACE TRIGGER STAR_Events_id_TRG 
BEFORE INSERT ON STAR_Events 
FOR EACH ROW 
WHEN (NEW.id IS NULL) 
BEGIN 
    SELECT STAR_Events_id_SEQ.NEXTVAL INTO :NEW.id FROM DUAL; 
END;
/

CREATE SEQUENCE STAR_Issue_id_SEQ 
    NOCACHE 
    ORDER ;

CREATE OR REPLACE TRIGGER STAR_Issue_id_TRG 
BEFORE INSERT ON STAR_Issue 
FOR EACH ROW 
WHEN (NEW.id IS NULL) 
BEGIN 
    SELECT STAR_Issue_id_SEQ.NEXTVAL INTO :NEW.id FROM DUAL; 
END;
/

CREATE SEQUENCE STAR_Jazyk_id_SEQ 
    NOCACHE 
    ORDER ;

CREATE OR REPLACE TRIGGER STAR_Jazyk_id_TRG 
BEFORE INSERT ON STAR_Jazyk 
FOR EACH ROW 
WHEN (NEW.id IS NULL) 
BEGIN 
    SELECT STAR_Jazyk_id_SEQ.NEXTVAL INTO :NEW.id FROM DUAL; 
END;
/

CREATE SEQUENCE STAR_Pocet_Issue_id_SEQ 
    NOCACHE 
    ORDER ;

CREATE OR REPLACE TRIGGER STAR_Pocet_Issue_id_TRG 
BEFORE INSERT ON STAR_Pocet_Issue 
FOR EACH ROW 
WHEN (NEW.id IS NULL) 
BEGIN 
    SELECT STAR_Pocet_Issue_id_SEQ.NEXTVAL INTO :NEW.id FROM DUAL; 
END;
/

CREATE SEQUENCE STAR_Pocet_clenov_timu_id_SEQ 
    NOCACHE 
    ORDER ;

CREATE OR REPLACE TRIGGER STAR_Pocet_clenov_timu_id_TRG 
BEFORE INSERT ON STAR_Pocet_clenov_timu 
FOR EACH ROW 
WHEN (NEW.id IS NULL) 
BEGIN 
    SELECT STAR_Pocet_clenov_timu_id_SEQ.NEXTVAL INTO :NEW.id FROM DUAL; 
END;
/

CREATE SEQUENCE STAR_Pocet_issue_za_mesiac_id 
    NOCACHE 
    ORDER ;

CREATE OR REPLACE TRIGGER STAR_Pocet_issue_za_mesiac_id 
BEFORE INSERT ON STAR_Pocet_issue_za_mesiac 
FOR EACH ROW 
WHEN (NEW.id IS NULL) 
BEGIN 
    SELECT STAR_Pocet_issue_za_mesiac_id.NEXTVAL INTO :NEW.id FROM DUAL; 
END;
/

CREATE SEQUENCE STAR_Pocet_issue_za_rok_id_SEQ 
    NOCACHE 
    ORDER ;

CREATE OR REPLACE TRIGGER STAR_Pocet_issue_za_rok_id_TRG 
BEFORE INSERT ON STAR_Pocet_issue_za_rok 
FOR EACH ROW 
WHEN (NEW.id IS NULL) 
BEGIN 
    SELECT STAR_Pocet_issue_za_rok_id_SEQ.NEXTVAL INTO :NEW.id FROM DUAL; 
END;
/

CREATE SEQUENCE STAR_Pocet_pouzivatelov_id_SEQ 
    NOCACHE 
    ORDER ;

CREATE OR REPLACE TRIGGER STAR_Pocet_pouzivatelov_id_TRG 
BEFORE INSERT ON STAR_Pocet_pouzivatelov 
FOR EACH ROW 
WHEN (NEW.id IS NULL) 
BEGIN 
    SELECT STAR_Pocet_pouzivatelov_id_SEQ.NEXTVAL INTO :NEW.id FROM DUAL; 
END;
/

CREATE SEQUENCE STAR_Pouzivatelia_id_SEQ 
    NOCACHE 
    ORDER ;

CREATE OR REPLACE TRIGGER STAR_Pouzivatelia_id_TRG 
BEFORE INSERT ON STAR_Pouzivatelia 
FOR EACH ROW 
WHEN (NEW.id IS NULL) 
BEGIN 
    SELECT STAR_Pouzivatelia_id_SEQ.NEXTVAL INTO :NEW.id FROM DUAL; 
END;
/

CREATE SEQUENCE STAR_Povod_id_SEQ 
    NOCACHE 
    ORDER ;

CREATE OR REPLACE TRIGGER STAR_Povod_id_TRG 
BEFORE INSERT ON STAR_Povod 
FOR EACH ROW 
WHEN (NEW.id IS NULL) 
BEGIN 
    SELECT STAR_Povod_id_SEQ.NEXTVAL INTO :NEW.id FROM DUAL; 
END;
/

CREATE SEQUENCE STAR_Repository_id_SEQ 
    NOCACHE 
    ORDER ;

CREATE OR REPLACE TRIGGER STAR_Repository_id_TRG 
BEFORE INSERT ON STAR_Repository 
FOR EACH ROW 
WHEN (NEW.id IS NULL) 
BEGIN 
    SELECT STAR_Repository_id_SEQ.NEXTVAL INTO :NEW.id FROM DUAL; 
END;
/

CREATE SEQUENCE STAR_Tim_id_SEQ 
    NOCACHE 
    ORDER ;

CREATE OR REPLACE TRIGGER STAR_Tim_id_TRG 
BEFORE INSERT ON STAR_Tim 
FOR EACH ROW 
WHEN (NEW.id IS NULL) 
BEGIN 
    SELECT STAR_Tim_id_SEQ.NEXTVAL INTO :NEW.id FROM DUAL; 
END;
/

CREATE SEQUENCE STAR_mesiace_roky_id_SEQ 
    NOCACHE 
    ORDER ;

CREATE OR REPLACE TRIGGER STAR_mesiace_roky_id_TRG 
BEFORE INSERT ON STAR_mesiace_roky 
FOR EACH ROW 
WHEN (NEW.id IS NULL) 
BEGIN 
    SELECT STAR_mesiace_roky_id_SEQ.NEXTVAL INTO :NEW.id FROM DUAL; 
END;
/

CREATE SEQUENCE STAR_roky_id_SEQ 
    NOCACHE 
    ORDER ;

CREATE OR REPLACE TRIGGER STAR_roky_id_TRG 
BEFORE INSERT ON STAR_roky 
FOR EACH ROW 
WHEN (NEW.id IS NULL) 
BEGIN 
    SELECT STAR_roky_id_SEQ.NEXTVAL INTO :NEW.id FROM DUAL; 
END;
/



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            15
-- CREATE INDEX                            20
-- ALTER TABLE                             33
-- CREATE VIEW                              0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                          15
-- ALTER TRIGGER                            0
-- CREATE STRUCTURED TYPE                   0
-- CREATE COLLECTION TYPE                   0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                         15
-- CREATE MATERIALIZED VIEW                 0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
